# Generated by Django 4.2.27 on 2025-12-24 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('web', 'Web Development'), ('mobile', 'Mobile Development'), ('data', 'Data Science & ML'), ('hardware', 'Hardware & Embedded'), ('design', 'Design & UI/UX'), ('devops', 'DevOps & Cloud'), ('database', 'Databases'), ('tools', 'Tools & Frameworks'), ('soft', 'Soft Skills'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, 'Post-Graduate')])),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Portfolio URL')),
                ('resume_url', models.URLField(blank=True, null=True, verbose_name='Resume URL')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('looking_for_team', models.BooleanField(default=True)),
                ('open_to_mentorship', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='profiles.studentprofile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_views',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
